---
abstract: 'AnyEvent::Handle subclass for serial ports'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-SerialPort
requires:
  AnyEvent::Handle: 0
  Carp: 0
  Device::SerialPort: 0
  Fcntl: 0
  Symbol: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/beanz/anyevent-serialport-perl/issues
  repository: git://github.com/beanz/anyevent-serialport-perl.git
version: 1.130171
